//
// Generated file, do not edit! Created by nedtool 5.5 from Demo/msg/Demo_Piece_list.msg.
//

#ifndef __VEINS_DEMO_PIECE_LIST_M_H
#define __VEINS_DEMO_PIECE_LIST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "veins/modules/messages/BaseFrame1609_4_m.h"
// }}


namespace veins {

/**
 * Class generated from <tt>Demo/msg/Demo_Piece_list.msg:10</tt> by nedtool.
 * <pre>
 * packet Demo_Piece_list extends BaseFrame1609_4
 * {
 *     int serial;
 *     string list;
 *     LAddress::L2Type senderAddress = -1;
 * }
 * </pre>
 */
class Demo_Piece_list : public ::veins::BaseFrame1609_4
{
  protected:
    int serial;
    ::omnetpp::opp_string list;
    LAddress::L2Type senderAddress;

  private:
    void copy(const Demo_Piece_list& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Demo_Piece_list&);

  public:
    Demo_Piece_list(const char *name=nullptr, short kind=0);
    Demo_Piece_list(const Demo_Piece_list& other);
    virtual ~Demo_Piece_list();
    Demo_Piece_list& operator=(const Demo_Piece_list& other);
    virtual Demo_Piece_list *dup() const override {return new Demo_Piece_list(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSerial() const;
    virtual void setSerial(int serial);
    virtual const char * getList() const;
    virtual void setList(const char * list);
    virtual LAddress::L2Type& getSenderAddress();
    virtual const LAddress::L2Type& getSenderAddress() const {return const_cast<Demo_Piece_list*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Demo_Piece_list& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Demo_Piece_list& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_DEMO_PIECE_LIST_M_H

